kind: ConfigMap
apiVersion: v1
metadata:
  name: home-assistant-configmap
data:
  known_devices.yaml: |

  automations.yaml: |

  configuration.yaml: |-
    default_config:
    homeassistant:
      name: dev
      latitude: "45.495461961982286"
      longitude: "9.145847260951998"
      elevation: 150
      unit_system: metric
      time_zone: Europe/Rome
    frontend:
      themes: !include_dir_merge_named themes
    automation: !include automations.yaml
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
        - 100.64.0.0/10
        - 127.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16