apiVersion: v1
kind: Service
metadata:
  labels:
    app: home-assistant
  name: home-assistant
spec:
  ports:
    - name: home-assistant
      port: 8123
      targetPort: http
  selector:
    app: home-assistant
