apiVersion: v1
kind: Service
metadata:
  labels:
    app: inim-mqtt
    group: inim-mqtt
  name: inim-mqtt
spec:
  ports:
    - name: web
      port: 5000
      targetPort: 5000
  selector:
    app: inim-mqtt
    group: inim-mqtt
