apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    group: inim-mqtt
  name: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis
    group: inim-mqtt
