apiVersion: v1
kind: Service
metadata:
  labels:
    app: mqtt
    group: inim-mqtt
  name: mqtt
spec:
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
  selector:
    app: mqtt
    group: inim-mqtt
