apiVersion: v1
stringData:
  users.list: |
    admin:$7$101$jTuC283hGvQbj9x9$A9t5xOYVpvIsrAdhqp/GREwvkEw/3chhptP6s74O9ysbQpoSm0rfLyt8v52aJvAapVI8qgYpGEG2iLkpNBoRRQ==
  mosquitto.conf: |
    allow_anonymous false
    password_file /mosquitto/data/users.list
    listener 1883 0.0.0.0
kind: Secret
metadata:
  name: mqtt